/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAgenteNavegadorRouteImport } from './routes/_authenticated/agente-navegador'
import { Route as AuthenticatedCampanhasRouteImport } from './routes/_authenticated/campanhas'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDecisoesRouteImport } from './routes/_authenticated/decisoes'
import { Route as AuthenticatedDiagnosticoRouteImport } from './routes/_authenticated/diagnostico'
import { Route as AuthenticatedEstrategistaRouteImport } from './routes/_authenticated/estrategista'
import { Route as AuthenticatedIntegracoesRouteImport } from './routes/_authenticated/integracoes'
import { Route as AuthenticatedNotasRouteImport } from './routes/_authenticated/notas'
import { Route as ApiPublicCronExecutarRouteImport } from './routes/api/public/cron/executar'
import { Route as ApiPublicOauthCallbackRouteImport } from './routes/api/public/oauth/callback'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgenteNavegadorRoute =
  AuthenticatedAgenteNavegadorRouteImport.update({
    id: '/agente-navegador',
    path: '/agente-navegador',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampanhasRoute = AuthenticatedCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDecisoesRoute = AuthenticatedDecisoesRouteImport.update({
  id: '/decisoes',
  path: '/decisoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnosticoRoute =
  AuthenticatedDiagnosticoRouteImport.update({
    id: '/diagnostico',
    path: '/diagnostico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstrategistaRoute =
  AuthenticatedEstrategistaRouteImport.update({
    id: '/estrategista',
    path: '/estrategista',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntegracoesRoute =
  AuthenticatedIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotasRoute = AuthenticatedNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicCronExecutarRoute = ApiPublicCronExecutarRouteImport.update({
  id: '/api/public/cron/executar',
  path: '/api/public/cron/executar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthCallbackRoute = ApiPublicOauthCallbackRouteImport.update({
  id: '/api/public/oauth/callback',
  path: '/api/public/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/agente-navegador': typeof AuthenticatedAgenteNavegadorRoute
  '/campanhas': typeof AuthenticatedCampanhasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/decisoes': typeof AuthenticatedDecisoesRoute
  '/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/estrategista': typeof AuthenticatedEstrategistaRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/notas': typeof AuthenticatedNotasRoute
  '/api/public/cron/executar': typeof ApiPublicCronExecutarRoute
  '/api/public/oauth/callback': typeof ApiPublicOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/agente-navegador': typeof AuthenticatedAgenteNavegadorRoute
  '/campanhas': typeof AuthenticatedCampanhasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/decisoes': typeof AuthenticatedDecisoesRoute
  '/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/estrategista': typeof AuthenticatedEstrategistaRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/notas': typeof AuthenticatedNotasRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/cron/executar': typeof ApiPublicCronExecutarRoute
  '/api/public/oauth/callback': typeof ApiPublicOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agente-navegador': typeof AuthenticatedAgenteNavegadorRoute
  '/_authenticated/campanhas': typeof AuthenticatedCampanhasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/decisoes': typeof AuthenticatedDecisoesRoute
  '/_authenticated/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/_authenticated/estrategista': typeof AuthenticatedEstrategistaRoute
  '/_authenticated/integracoes': typeof AuthenticatedIntegracoesRoute
  '/_authenticated/notas': typeof AuthenticatedNotasRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/cron/executar': typeof ApiPublicCronExecutarRoute
  '/api/public/oauth/callback': typeof ApiPublicOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agente-navegador'
    | '/campanhas'
    | '/configuracoes'
    | '/decisoes'
    | '/diagnostico'
    | '/estrategista'
    | '/integracoes'
    | '/notas'
    | '/api/public/cron/executar'
    | '/api/public/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/agente-navegador'
    | '/campanhas'
    | '/configuracoes'
    | '/decisoes'
    | '/diagnostico'
    | '/estrategista'
    | '/integracoes'
    | '/notas'
    | '/'
    | '/api/public/cron/executar'
    | '/api/public/oauth/callback'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agente-navegador'
    | '/_authenticated/campanhas'
    | '/_authenticated/configuracoes'
    | '/_authenticated/decisoes'
    | '/_authenticated/diagnostico'
    | '/_authenticated/estrategista'
    | '/_authenticated/integracoes'
    | '/_authenticated/notas'
    | '/_authenticated/'
    | '/api/public/cron/executar'
    | '/api/public/oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCronExecutarRoute: typeof ApiPublicCronExecutarRoute
  ApiPublicOauthCallbackRoute: typeof ApiPublicOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agente-navegador': {
      id: '/_authenticated/agente-navegador'
      path: '/agente-navegador'
      fullPath: '/agente-navegador'
      preLoaderRoute: typeof AuthenticatedAgenteNavegadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campanhas': {
      id: '/_authenticated/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof AuthenticatedCampanhasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decisoes': {
      id: '/_authenticated/decisoes'
      path: '/decisoes'
      fullPath: '/decisoes'
      preLoaderRoute: typeof AuthenticatedDecisoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostico': {
      id: '/_authenticated/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof AuthenticatedDiagnosticoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estrategista': {
      id: '/_authenticated/estrategista'
      path: '/estrategista'
      fullPath: '/estrategista'
      preLoaderRoute: typeof AuthenticatedEstrategistaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integracoes': {
      id: '/_authenticated/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AuthenticatedIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notas': {
      id: '/_authenticated/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof AuthenticatedNotasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/executar': {
      id: '/api/public/cron/executar'
      path: '/api/public/cron/executar'
      fullPath: '/api/public/cron/executar'
      preLoaderRoute: typeof ApiPublicCronExecutarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/callback': {
      id: '/api/public/oauth/callback'
      path: '/api/public/oauth/callback'
      fullPath: '/api/public/oauth/callback'
      preLoaderRoute: typeof ApiPublicOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgenteNavegadorRoute: typeof AuthenticatedAgenteNavegadorRoute
  AuthenticatedCampanhasRoute: typeof AuthenticatedCampanhasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDecisoesRoute: typeof AuthenticatedDecisoesRoute
  AuthenticatedDiagnosticoRoute: typeof AuthenticatedDiagnosticoRoute
  AuthenticatedEstrategistaRoute: typeof AuthenticatedEstrategistaRoute
  AuthenticatedIntegracoesRoute: typeof AuthenticatedIntegracoesRoute
  AuthenticatedNotasRoute: typeof AuthenticatedNotasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgenteNavegadorRoute: AuthenticatedAgenteNavegadorRoute,
  AuthenticatedCampanhasRoute: AuthenticatedCampanhasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDecisoesRoute: AuthenticatedDecisoesRoute,
  AuthenticatedDiagnosticoRoute: AuthenticatedDiagnosticoRoute,
  AuthenticatedEstrategistaRoute: AuthenticatedEstrategistaRoute,
  AuthenticatedIntegracoesRoute: AuthenticatedIntegracoesRoute,
  AuthenticatedNotasRoute: AuthenticatedNotasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCronExecutarRoute: ApiPublicCronExecutarRoute,
  ApiPublicOauthCallbackRoute: ApiPublicOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
